    drop table if exists author CASCADE;
    drop table if exists book cascade;
    drop table if exists book_genre CASCADE;
    drop table if exists comment CASCADE;
    drop table if exists genre CASCADE;


    create table authors(
       id_author bigint generated by default as identity,
        name_author VARCHAR(255) not null,
        year_author VARCHAR(255),
        unique (name_author),
        primary key (id_author)
    );

    create table books(
            id_book bigint generated by default as identity,
            name_book VARCHAR(255),
            year_book VARCHAR(255),
            id_author bigint,
            foreign key (id_author) references author(id_author)
            on delete cascade
            ON UPDATE CASCADE,
            primary key (id_book)
    );
     create table genres(
        id_genre bigint generated by default as identity,
        name_genre VARCHAR(255) not null,
        unique (name_genre),
        primary key (id_genre)
    );


      create table comments(
        id_comment bigint generated by default as identity,
        text VARCHAR(255) not null,
        id_book bigint,
        primary key (id_comment),
        foreign key (id_book) references book(id_book)
        on delete cascade
        ON UPDATE CASCADE
    );
    create table book_genre(
        id_book bigint not null,
        id_genre bigint not null ,

        foreign key (id_genre) references genre(id_genre)
        on delete cascade
        ON UPDATE CASCADE,
        foreign key (id_book) references book(id_book)
        on delete cascade
        ON UPDATE CASCADE
    );














