#use:
#  dataProvider: hibernate
spring:

  data:
    mongodb:
#      authentication-database: admin
      database: LibraryWeb
      port: 27017
      host: localhost
mongock:
  # runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - org.example.home.mongock.changelogs


#  datasource:
#    url: jdbc:h2:mem:book
#    username: egor
#    password: 123

#    schema: schema_book.sql
#    data: data.sql

#    url: jdbc:postgresql://localhost:5432/Library
#    username: postgres
#    password: westa852
#    initialization-mode: always

#  sql:
#    init:
#      mode: always
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: validate
#
#
#
#    properties:
#      hibernate:
#        format_sql: true